### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by nizartaha** [compas-dev/compas_gmsh#2]
launched anaconda 3 as administrator and followed the installation instructions but without compas_view2
`conda create -n gmsh -c conda-forge python=3.8 python-gmsh compas --yes`
then followed next step:
`(gmsh) C:\WINDOWS\system32>pip install -e .`
got error:
`ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: C:\WINDOWS\system32`

if i run the example , Mesh Remeshing, i get error:
```    
from compas_gmsh.models import MeshModel
ModuleNotFoundError: No module named 'compas_gmsh'
```

**Comment by brgcode** [comment]
you need to change the current working directory of the command line to the `compas_gmsh` root folder. the "dot" in `pip install -e .` refers to the current directory. currently you are in `C:\WINDOWS\system32` which indeed does not contain the required `setup.py` needed for the installation...

**Comment by nizartaha** [comment]
sorry forgot to write this as well. i did to
`(gmsh) C:\ProgramData\Anaconda3\envs\gmsh>pip install -e .`
error
`ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: C:\ProgramData\Anaconda3\envs\gmsh`

**Comment by brgcode** [comment]
no sorry, you misunderstand. you have to clone the repo onto your computer and then change to that folder... so something like

```bash
git clone https://github.com/compas-dev/compas_gmsh.git
cd compas_gmsh
pip install -e .
```

**Comment by brgcode** [comment]
the anaconda folder is the folder of the environment you just created but it doesn't contain the source code of the package...

you still have to create the env and activate it, but the pip installation procedure needs to be run from the local code repo

**Comment by nizartaha** [comment]
ok, installed. looks good so far.
one more error from compas_view2
```
File "C:\Users\username\.conda\envs\gmsh\lib\site-packages\compas_view2\objects\textobject.py", line 7, in <module>       
    import freetype as ft
ModuleNotFoundError: No module named 'freetype'
```

**Comment by brgcode** [comment]
did you install view2 from source or with `conda`?
in any case, just do
```bash
conda install freetype-py
```

**Comment by nizartaha** [comment]
it works now.
i installed it through `conda create -n gmsh -c conda-forge python=3.8 python-gmsh compas compas_view2 --yes`

**Comment by brgcode** [comment]
cool! would you mind adding an issue to `compas_view2` about the missing `freetype` package? this should already be taken care of in the `conda` distribution...
